sudo: false
language: objective-c
osx_image: xcode7
branches:
  only:
    - master
script:
- xctool -workspace 'ZendeskSDK Urban Airship Example App.xcworkspace' -scheme 'ZendeskSDK Urban Airship Example App' -sdk iphonesimulator -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO build
